module Isort
  class FileSorter
    @file_path: untyped

    def sort_and_format_imports: -> untyped

    def sort_directory: -> untyped

    def sort_imports: -> untyped

    private

    def extract_lines: -> untyped

    def extract_lines_with_comments: -> untyped

    def format_group: -> untyped
  end
end
